"""add document_images table and update status default

Revision ID: 0034d96e823e
Revises: 2966bee2ab70
Create Date: 2026-03-28 20:49:55.080661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0034d96e823e'
down_revision: Union[str, Sequence[str], None] = '2966bee2ab70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('kb_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt', sa.Text(), server_default='', nullable=False),
    sa.Column('context', sa.Text(), server_default='', nullable=False),
    sa.Column('section_title', sa.Text(), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('vision_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('image_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("idx_document_images_doc_id", "document_images", ["doc_id"])
    op.create_index("idx_document_images_kb_id", "document_images", ["kb_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_document_images_kb_id", table_name="document_images")
    op.drop_index("idx_document_images_doc_id", table_name="document_images")
    op.drop_table('document_images')
    # ### end Alembic commands ###
