"""add storage_key to documents

Revision ID: 2966bee2ab70
Revises: 37fbc0fa6104
Create Date: 2026-03-28 12:02:45.632484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2966bee2ab70'
down_revision: Union[str, Sequence[str], None] = '37fbc0fa6104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'storage_key')
    # ### end Alembic commands ###
