"""add status and error_msg to documents

Revision ID: 37fbc0fa6104
Revises: 82ff677b19b3
Create Date: 2026-03-27 21:06:04.941791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fbc0fa6104'
down_revision: Union[str, Sequence[str], None] = '82ff677b19b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.String(length=20), server_default='processing', nullable=False))
    op.add_column('documents', sa.Column('error_msg', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_msg')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
