"""add server defaults and rename engine to parse_engine

Revision ID: 82ff677b19b3
Revises: 704e8abb54e2
Create Date: 2026-03-27 15:52:09.290419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ff677b19b3'
down_revision: Union[str, Sequence[str], None] = '704e8abb54e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parse_engine', sa.String(length=50), server_default='', nullable=False))
    op.drop_column('documents', 'engine')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('engine', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('documents', 'parse_engine')
    # ### end Alembic commands ###
